apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJwcm9qZWN0a2Rldm9wcy5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYTJ0eVpXUmtlVFF5TVVCbmJXRnBiQzVqYjIwNk1EaDNNVEZCTURReUlRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson